---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  environment:
    CEP_ID: com.aedt.adobe-ide
    CEP_NOTARIZE_USERNAME:
      from_secret: CEP_NOTARIZE_USERNAME
    CEP_NOTARIZE_APP_PASSWORD:
      from_secret: CEP_NOTARIZE_APP_PASSWORD
  commands:
    - ./ci.sh


kind: pipeline
type: exec
name: build-installers

steps:
- name: build
  environment:
    CEP_ID: com.aedt.adobe-ide
    CEP_NOTARIZE_USERNAME:
      from_secret: CEP_NOTARIZE_USERNAME
    CEP_NOTARIZE_APP_PASSWORD:
      from_secret: CEP_NOTARIZE_APP_PASSWORD
    GITHUB_API_KEY:
      from_secret: GITHUB_API_KEY
  commands:
    - ./scripts/ci.sh