---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  commands:
    - export HOME=/Users/koen
    - export PATH=$HOME/bin:/usr/local/bin:$PATH
    - export NVM_DIR="$HOME/.nvm"
    - "[ -s \"/usr/local/opt/nvm/nvm.sh\" ]"
    - ". \"/usr/local/opt/nvm/nvm.sh\""
    - nvm use 10
    - npm install
    - npm run build-installers