os:
- osx
language: node_js
node_js:
- '10'
before_install:
- npm i -g npm@6.4.1
- brew install makensis
script: npm run build-installers
deploy:
  provider: releases
  api_key:
    secure: vCz90uPzfLke5HIMYfA9kO6hAXKrTB31lvZYBMc+OBnbrBv/boCrca/04uf7AXpCrgHKjpvJ/lgGzvaFL2NAhEuMA0he3jhl8Km4rvbUi+q4oC59p63A18uzst1zfvVSZEH5GDW4wVjCXtwiCL1kh9nZDk5HgpNduK/UhB2pHBWHPrQDEHzFvTrXA/cZJoW/1Qb9x6pySIF4+IB0DCFEbFAmuGG4Yb2iKalIdR3PBID7L1YV85l8IKjuvmJEbN+XqLY+eQTWFX8pYNYtAYzf6t51jpt41lHN7JKKSg0EWDsnYr1Y9ytYmNN0oQYRCcQhGube3aRlIosBwjn2H4DGuL7Ll0q5TQNtznHSiG+vyVv7+irnMx7lV8zeVG6V25IibjBPY3kadTsraxwk3WbcBsZqHHvH7exUu0y+OpHju1j+7PbU32ugbEHhY6tVaqT2zMP3T8eC11rIxQNHRGuFsMFMDnL0HhWuOnshiC4o0zUm1XUb0qVMnc3lC5pXBeW0CN5svCsqPU0dtFTyF1Xx7ZeVzkNjeAeBzftiVaLT6HuE7/wAAdJyCU3upLALfVgbs+nCTmE+ovGWQsD2+ftEJVkYtT8o67BfLwzJ9fofL8UxgrKtmJM3FfzIfZguDI9aZf9WIPgX9VPQ0iqrieX3oMkWdMCuVg6+YW7GTA1usdQ=
  file: 
    - archive/adobe-ide-0.0.1.exe
    - archive/adobe-ide-0.0.1.pkg
  on:
    repo: adobe-extension-tools/adobe-ide
